#!/usr/bin/env python3
"""Run the peer-review slop judge against a labelled corpus to establish whether it
can separate known machine-generated content from known human writing.

The prompt is the SAME judging philosophy and the SAME 0-100 scale as the peer-review
run, with the genre noun swapped (review -> article). It is therefore a validation of
the instrument's discriminative ability, not a bit-identical replay.
"""
import json,asyncio,collections,statistics as st,random
from pydantic import BaseModel
from typing import Literal
import anthropic

class Judgment(BaseModel):
    llm_likelihood: int
    primary_signal: str
    signal_type: Literal["typography","vocabulary","structure","substance","none"]

SYSTEM = """You are judging whether a piece of technical writing was substantially
generated by a large language model, or written by a human author.

Judge the WRITING, not its quality. A short, blunt, or poorly written piece is often
strongly human. A fluent, well-organised piece is not automatically machine-written --
many authors write well, and many use a model only to fix grammar, which is not
"substantially generated".

Signals a human wrote it: specific concrete detail that only someone who did the work
would have (real error messages, version numbers, dead ends, things that went wrong),
idiosyncratic voice, strong opinions, non-native English phrasing, uneven structure,
digressions.

Signals of machine generation: generic content that could apply to any topic in the
category, symmetric scaffolding, fluent prose with no concrete specifics, listicle
structure with uniform section lengths, definitions of things the reader already knows,
no evidence the author has personally done what they describe.

Return a likelihood from 0 (certainly human) to 100 (certainly machine-generated)."""
import os
DATA = os.environ.get("PRP_DATA", "_data")   # collected notes; override with PRP_DATA
OUT  = os.environ.get("PRP_OUT", ".")       # figures/CSVs written here

async def main():
    rows=[json.loads(l) for l in open(f"{DATA}/calib.jsonl")]
    print(f"judging {len(rows)} articles blind: {dict(collections.Counter(r['label'] for r in rows))}",flush=True)
    client=anthropic.AsyncAnthropic(); sem=asyncio.Semaphore(12); out=[]
    async def one(it):
        async with sem:
            for a in range(4):
                try:
                    r=await client.messages.parse(model="claude-opus-5",max_tokens=2000,
                        output_config={"effort":"low"},system=SYSTEM,
                        messages=[{"role":"user","content":it["text"][:9000]}],
                        output_format=Judgment)
                    j=r.parsed_output
                    out.append({"cid":it["cid"],"label":it["label"],"domain":it.get("domain"),
                                "score":j.llm_likelihood,"stype":j.signal_type,
                                "signal":j.primary_signal})
                    return
                except anthropic.RateLimitError: await asyncio.sleep(8*(a+1))
                except Exception as e:
                    if a==3: print("  ERR",type(e).__name__,str(e)[:90],flush=True)
                    else: await asyncio.sleep(4*(a+1))
    tasks=[asyncio.create_task(one(r)) for r in rows]
    done=0
    for f in asyncio.as_completed(tasks):
        await f; done+=1
        if done%100==0: print(f"  {done}/{len(rows)}",flush=True)
    with open(f"{DATA}/calib_judgments.jsonl","w") as fh:
        for o in out: fh.write(json.dumps(o)+"\n")
    print(f"DONE {len(out)}",flush=True)
asyncio.run(main())
